import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Provider from './provider';
import { Toaster } from 'sonner';
import { AuthContextProvider } from '@/context/AuthContext';
import { CheckCircle, XCircle, AlertCircle, Info, Loader2 } from 'lucide-react';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'AI Agent',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
          <AuthContextProvider>
            {children}
            <Toaster
              position="top-right"
              expand={false}
              richColors
              closeButton
              duration={4000}
              visibleToasts={4}
              gap={12}
              toastOptions={{
                style: {
                  background: 'white',
                  border: '1px solid #e5e7eb',
                  borderRadius: '12px',
                  padding: '14px 16px',
                  boxShadow: '0 10px 40px -10px rgba(0, 0, 0, 0.15)',
                  fontSize: '14px',
                },
                className: 'sonner-toast',
              }}
            />
          </AuthContextProvider>
        </Provider>
      </body>
    </html>
  );
}
